<?php require VIEWS_PATH . '/admin/includes/header.phtml';?>
<div class="container">
    <div class="col-md-12">
		<?php require VIEWS_PATH . 'includes/messages.phtml';?>
    </div>

    <div class="col-md-12">
        <h1>User - <small>Edição de Usuário</small></h1>
        <hr>
    </div>
    <div class="col-md-12">
        <form method="post" action="<?=HOME;?>/users/edit/<?=$this->user['id'];?>">
            <div class="form-group">
                <label for="exampleInputEmail1">Nome</label>
                <input type="text" name="first_name" class="form-control" value="<?=$this->user['first_name'];?>">
            </div>

            <div class="form-group">
                <label for="exampleInputEmail1">Sobrenome</label>
                <input type="text" name="last_name" class="form-control" value="<?=$this->user['last_name'];?>">
            </div>

            <div class="form-group">
                <label for="exampleInputEmail1">Senha</label>
                <input type="password" name="password" class="form-control" placeholder="Se você quiser alterar sua senha, preencha o campo e confirme abaixo...">
            </div>

            <div class="form-group">
                <label for="exampleInputEmail1">Confirmar Senha</label>
                <input type="password" name="password_confirm" class="form-control">
            </div>

            <button type="submit" class="btn btn-success btn-lg pull-right">Salvar Usuário</button>
        </form>
    </div>
</div>
<?php require VIEWS_PATH . '/admin/includes/footer.phtml';?>
