<?php require VIEWS_PATH . 'includes/header.phtml';?>

<div class="container">

    <div class="col-md-12">
		<?php require VIEWS_PATH . 'includes/messages.phtml';?>
    </div>

	<div class="col-md-12">
		<h1>Users - <small>Cadastrar novo usuário</small></h1>
		<hr>
	</div>
	<div class="col-md-12">
		<form method="post" action="<?=HOME;?>/users/new">
			<div class="form-group">
				<label for="exampleInputEmail1">Nome</label>
				<input type="text" name="first_name" class="form-control">
			</div>

            <div class="form-group">
                <label for="exampleInputEmail1">Sobrenome</label>
                <input type="text" name="last_name" class="form-control">
            </div>

			<div class="form-group">
				<label for="exampleInputPassword1">Username</label>
                <input type="text" name="username" class="form-control">
            </div>

            <div class="form-group">
                <label for="exampleInputEmail1">Senha</label>
                <input type="password" name="password" class="form-control">
            </div>

            <div class="form-group">
                <label for="exampleInputEmail1">Confirmar Senha</label>
                <input type="password" name="password_confirm" class="form-control">
            </div>

            <button type="submit" class="btn btn-success btn-lg pull-right">Salvar Usuário</button>
		</form>
	</div>
</div>
<?php require VIEWS_PATH . 'includes/footer.phtml';?>
