<?php require VIEWS_PATH . 'includes/header.phtml';?>
<div class="container">

    <div class="jumbotron">
        <h1>Bem Vindo ao Projeto Um</h1>
        <p>
            Projeto criado no curso PHP Orientado a Objetos da Code Experts Learning.
        </p>
        <p>
            <a class="btn btn-lg btn-primary" href="http://bit.ly/ce-learn" role="button">Saiba mais &raquo;</a>
        </p>
    </div>

</div>
<?php require VIEWS_PATH . 'includes/footer.phtml';?>
