<?php require VIEWS_PATH . 'includes/header.phtml';?>
<div class="container">

	<div class="jumbotron">
		<h1>Sobre</h1>
	</div>
	<div class="col-md-12">
		<h2>A Instituição</h2>
		<p>
			Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maiores minima
			molestias optio unde? Assumenda, consequuntur maxime! Aliquid eius est, et in
			magni nesciunt nostrum, numquam pariatur qui repellendus ullam voluptate.
		</p>
		<p>
			Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maiores minima
			molestias optio unde? Assumenda, consequuntur maxime! Aliquid eius est, et in
			magni nesciunt nostrum, numquam pariatur qui repellendus ullam voluptate.
		</p>
		<h2>Nossas Metas</h2>
		<p>
			Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maiores minima
			molestias optio unde? Assumenda, consequuntur maxime! Aliquid eius est, et in
			magni nesciunt nostrum, numquam pariatur qui repellendus ullam voluptate.
		</p>

		<h2>Valores</h2>
		<p>
			Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maiores minima
			molestias optio unde? Assumenda, consequuntur maxime! Aliquid eius est, et in
			magni nesciunt nostrum, numquam pariatur qui repellendus ullam voluptate.
		</p>
	</div>
</div>
<?php require VIEWS_PATH . 'includes/footer.phtml';?>
