<?php require VIEWS_PATH . 'includes/header.phtml';?>
<div class="container">
	<div class="col-md-12">
		<h1>Cadastrar nova despesa</h1>
		<hr>
	</div>
	<div class="col-md-12">
		<form method="post" action="<?=HOME;?>/myexpenses/new">
			<div class="form-group">
				<label for="exampleInputEmail1">Valor Gasto</label>
				<input type="text" name="value" class="form-control" id="exampleInputEmail1" placeholder="Valor gasto...">
			</div>

			<div class="form-group">
				<label for="exampleInputEmail1">Categoria</label>
				<select name="categories_id">
					<?php foreach($this->categories as $c): ?>
					<option value="<?=$c['id']?>"><?=$c['name']?></option>
					<?php endforeach; ?>
				</select>
			</div>

			<div class="form-group">
				<label for="exampleInputPassword1">Descrição</label>
				<textarea name="description" id="" cols="30" rows="10" class="form-control"></textarea>
			</div>
			<button type="submit" class="btn btn-success btn-lg pull-right">Salvar Despesa</button>
		</form>
	</div>

</div>
<?php require VIEWS_PATH . 'includes/footer.phtml';?>
