<?php require VIEWS_PATH . '/admin/includes/header.phtml';?>
<div class="container content">
	<div class="col-md-12">
		<?php require VIEWS_PATH . 'includes/messages.phtml';?>
	</div>
	<div class="col-md-4 col-md-offset-4">
		<form action="<?=HOME;?>/auth/login" method="post">
			<div class="form-group">
				<label for="exampleInputEmail1">Email</label>
				<input type="email" class="form-control" placeholder="Email" name="email">
			</div>
			<div class="form-group">
				<label for="exampleInputPassword1">Password</label>
				<input type="password" class="form-control" placeholder="Senha" name="password">
			</div>
			<button type="submit" class="btn btn-default btn-success pull-right">Acessar</button>
		</form>
	</div>
</div>
<?php require VIEWS_PATH . '/admin/includes/footer.phtml';?>
