<?php require VIEWS_PATH . 'includes/header.phtml';?>
<div class="container">
    <div class="col-md-12">
        <div class="col-md-7 pull-left">
            <div class="row">
                <h1><?=$this->category;?></h1>
                <hr>
            </div>
	        <?php foreach($this->posts as $post): ?>
                <div class="row">
                    <h2>
                        <a href="<?=HOME . '/post/' . $post['slug'];?>">
					        <?=$post['title'];?>
                        </a>
                    </h2>
                    <small>Criado em <?=date('d/M/Y H:i:s', strtotime($post['created_at']));?></small>
                    <p>
				        <?=$post['description'];?>
                    </p>
                </div>
	        <?php endforeach;?>
        </div>

        <div class="col-md-4 pull-right">
            <div class="row">
                <h3>Sidebar</h3>
                <hr>
            </div>
            <div class="row content">
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                    Consequuntur hic id magnam, molestias nam nihil nulla obcaecati
                    placeat! At distinctio ducimus eaque iusto, magni quis suscipit.
                    Nulla omnis quas repellat.
                </p>
            </div>
        </div>
    </div>
</div>
<?php require VIEWS_PATH . 'includes/footer.phtml';?>
