<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport"
	      content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Projeto Final - Loja Virtual</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
        .mb30 {
            margin-bottom: 30px;
        }
    </style>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light mb30">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
				<span class="navbar-toggler-icon"></span>
			</button>
			<a class="navbar-brand" href="<?=HOME;?>">Code Experts Learning Store</a>
		</div>
		<div id="navbar" class="navbar-collapse collapse">
			<ul class="navbar-nav">
				<li class="nav-item">
					<a href="<?=HOME;?>/" class="nav-link">Home</a>
				</li>
            </ul>
		</div><!--/.nav-collapse -->
        <div class="float-right">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href="<?=HOME;?>/orders/my" class="nav-link">Meus Pedidos</a>
                </li>
                <li class="nav-item">
                    <a href="<?=HOME;?>/cart" class="nav-link">
                        <?php if(\Code\Session\Session::has('cart')): ?>
                            <span class="badge badge-danger">
                                <?=count(\Code\Session\Session::get('cart'));?>
                            </span>
                        <?php endif;?>
                        <i class="fa fa-shopping-cart fa-2x"></i>
                    </a>
                </li>
            </ul>
        </div>
	</div><!--/.container-fluid -->
</nav>
<div class="container">