<?php require VIEWS_PATH . 'includes/header.phtml';?>

<div class="container">

    <div class="col-md-12">
		<?php require VIEWS_PATH . 'includes/messages.phtml';?>
    </div>

    <div class="col-md-12">
        <h1>Categories - <small>Editar categoria</small></h1>
        <hr>
    </div>
    <div class="col-md-12">
        <form method="post" action="<?=HOME;?>/categories/edit/<?=$this->category['id'];?>">
            <div class="form-group">
                <label for="exampleInputEmail1">Nome</label>
                <input type="text" name="name" class="form-control" value="<?=$this->category['name'];?>">
            </div>

            <div class="form-group">
                <label for="exampleInputPassword1">Descrição</label>
                <textarea name="description" id="" cols="30" rows="10" class="form-control"><?=$this->category['description'];?></textarea>
            </div>

            <button type="submit" class="btn btn-success btn-lg pull-right">Atualizar Categoria</button>
        </form>
    </div>
</div>
<?php require VIEWS_PATH . 'includes/footer.phtml';?>
