<?php require VIEWS_PATH . 'includes/header.phtml';?>
<div class="container">
	<div class="col-md-12">
		<h1>Categories - <small>Gerencie suas categorias</small>
            <a href="<?=HOME . '/categories/new';?>" class="btn btn-success pull-right">Criar Nova Categoria</a>
        </h1>
		<hr>
	</div>

    <div class="col-md-12">
	    <?php require VIEWS_PATH . 'includes/messages.phtml';?>
    </div>

	<div class="col-md-12">
		<table class="table">
			<thead>
			<tr>
				<th>#</th>
				<th>Nome</th>
				<th>Criado em</th>
				<th></th>
			</tr>
			</thead>
			<tbody>
			<?php foreach($this->categories as $p):?>
			<tr>
				<td><?=$p['id'];?></td>
				<td><?=$p['name'];?></td>
				<td><?=date('d/m/Y H:i:s', strtotime($p['created_at']));?></td>
				<td>
					<a href="<?=HOME;?>/categories/edit/<?=$p['id'];?>" class="btn btn-default">
						Editar
					</a>
					<a href="<?=HOME;?>/categories/remove/<?=$p['id'];?>" class="btn btn-danger">
						Excluir
					</a>
				</td>
			</tr>
			<?php endforeach;?>
			</tbody>
		</table>
	</div>

</div>
<?php require VIEWS_PATH . 'includes/footer.phtml';?>
