<?php require VIEWS_PATH . 'includes/header.phtml';?>
<div class="container">
    <div class="col-md-12">
		<?php require VIEWS_PATH . 'includes/messages.phtml';?>
    </div>

    <div class="col-md-12">
        <h1>Posts - <small>Edição de Postagem</small></h1>
        <hr>
    </div>
    <div class="col-md-12">
        <form method="post" action="<?=HOME;?>/posts/edit/<?=$this->post['id'];?>">
            <div class="form-group">
                <label for="exampleInputEmail1">Titulo</label>
                <input type="text" name="title" class="form-control" value="<?=$this->post['title'];?>">
            </div>

            <div class="form-group">
                <label for="exampleInputEmail1">Descrição</label>
                <input type="text" name="description" class="form-control" value="<?=$this->post['description'];?>">
            </div>

            <div class="form-group">
                <label for="exampleInputPassword1">Conteúdo</label>
                <textarea name="content" id="" cols="30" rows="10" class="form-control"><?=$this->post['content'];?></textarea>
            </div>

            <div class="form-group">
                <label for="exampleInputEmail1">Tipo</label>
                <select name="type" class="form-control">
                    <option value="">Selecione o tipo do conteúdo</option>
                    <option value="post" <?php if($this->post['type'] == 'post'): ?> selected <?php endif; ?>>Post</option>
                    <option value="page" <?php if($this->post['type'] == 'page'): ?> selected <?php endif; ?>>Página</option>
                </select>
            </div>

            <div class="form-group">
                <label for="exampleInputEmail1">Categoria</label>
                <select name="category_id" class="form-control">
                    <option value="">Selecione uma categoria</option>
			        <?php foreach($this->categories as $p): ?>
                        <option value="<?=$p['id'];?>"
                                <?php if($this->post['category_id'] == $p['id']): ?> selected <?php endif;?>
                        ><?=$p['name'];?></option>
			        <?php endforeach;?>
                </select>
            </div>


            <div class="form-group">
                <label for="exampleInputEmail1">Autor</label>
                <select name="user_id" class="form-control">
                    <option value="">Selecione o autor</option>
					<?php foreach($this->users as $u): ?>
                        <option value="<?=$u['id'];?>"
                                <?php if($this->post['user_id'] == $u['id']): ?> selected <?php endif; ?>
                        ><?=$u['first_name'] . ' ' . $u['last_name'];?></option>
					<?php endforeach;?>
                </select>
            </div>

            <button type="submit" class="btn btn-success btn-lg pull-right">Atualizar Post</button>
        </form>
    </div>
</div>
<?php require VIEWS_PATH . 'includes/footer.phtml';?>
