<?php require VIEWS_PATH . '/admin/includes/header.phtml';?>
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<h2>Criar Produto</h2>
				<hr>
			</div>
		</div>

		<div class="col-md-12">
			<?php require VIEWS_PATH . 'includes/messages.phtml';?>
		</div>

		<div class="row">
			<form action="<?=HOME;?>/admin/products/new" method="post" enctype="multipart/form-data">
				<div class="col-md-12">
					<div class="form-group">
						<label>Nome do produto</label>
						<input type="text" class="form-control" name="name">
					</div>
				</div>

				<div class="col-md-12">
					<div class="form-group">
						<label>Descrição</label>
						<input type="text" class="form-control" name="description">
					</div>
				</div>

				<div class="col-md-12">
					<div class="form-group">
						<label>Conteúdo</label>
						<textarea name="content" class="form-control"></textarea>
					</div>
				</div>

				<div class="col-md-12">

					<div class="row">

						<div class="col-md-6">
							<div class="form-group">
								<label>Preço</label>
								<input type="text" class="form-control" name="price">
							</div>
						</div>

						<div class="col-md-6">
							<label>Status produto</label>
							<select name="is_active" class="form-control">
								<option value="A">Ativo</option>
								<option value="I">Inativo</option>
							</select>
						</div>

					</div>
				</div>

                <div class="col-md-12">
                    <div class="form-group">
                        <label>Selecione as imagens do produto</label>
                        <input type="file" name="images[]" multiple class="form-control">
                    </div>
                </div>

                <div class="col-md-12">
                    <div class="form-group">
                        <label>Selecione as Categorias para este Produto</label>
                        <select name="categories[]" class="form-control" multiple>
                            <?php foreach($this->categories as $c): ?>
                                <option value="<?=$c['id'];?>"><?=$c['name'];?></option>
                            <?php endforeach;?>
                        </select>
                    </div>
                </div>

				<div class="col-md-12">
					<button type="submit" class="btn btn-lg btn-success">Criar Produto</button>
				</div>
			</form>
		</div><!-- Fechamento da row dos inputs -->

	</div>
<?php require VIEWS_PATH . '/admin/includes/footer.phtml';?>