<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Página Inicial Do Painel</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<style>
		.content {
			margin-top: 80px;
		}
	</style>
</head>
<body>
<nav class="navbar navbar-inverse">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="<?=HOME;?>">Loja Admin</a>
		</div>
		<div id="navbar" class="collapse navbar-collapse">
			<ul class="nav navbar-nav">
				<?php if(\Code\Session\Session::has('user')): ?>
					<li>
						<a href="<?=HOME;?>/admin/products">Produtos</a>
					</li>
					<li>
						<a href="<?=HOME;?>/admin/categories">Categorias</a>
					</li>
					<li>
						<a href="<?=HOME;?>/admin/users">Usuários</a>
					</li>
					<li>
						<a href="<?=HOME;?>/auth/logout">Deslogar</a>
					</li>
				<?php else: ?>
					<li>
						<a href="<?=HOME;?>/">Ir para Site</a>
					</li>
				<?php endif;?>
			</ul>
		</div><!--/.nav-collapse -->
	</div>
</nav>